### PR TITLE
Support CircleCI test report

### LINKED ISSUE #168: Make use of CircleCI test report
https://circleci.com/docs/1.0/test-metadata/#for-django

It outputs on CircleCI how many tests ran, how many failed and what's the slowest test case with how long it took to run this given test case.

### PR DESCRIPTION
**Pull request by chocoelho**
## Description

Make use of CircleCI test report and usage of pytest as the test runner. Pytest also makes it easier to generate JUnit compatible XML. Resolves #168.

Also, pytest exists with code 5 if no tests ran and in order to solve it I had to add a placeholder test.

## Motivation and Context

With test report on CircleCI configured, users can have an overview of how many tests executed, how many failed and what is the slowest test case.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires documentation updates.
- [x] I have updated the documentation accordingly.
- [x] My change requires dependencies updates.
- [x] I have updated the dependencies accordingly.

### CODE REVIEW

**Comment by chocoelho** [comment]
Builds are failing because of fixmydjango dependency as it does not support Django 2 yet and doesn't pin a max version of it on `install_requires`. Once https://github.com/fixmydjango/fixmydjango-lib/pull/18 is merged, builds will run fine.

**Comment by filipeximenes** [comment]
@chocoelho merged and pushed to PyPI

**Comment by chocoelho** [comment]
Thanks, @filipeximenes. It worked perfectly.

**Comment by chocoelho** [comment]
It'll be good to test it along with #155, since the result will be displayed on an actual project using this boilerplate.

**Comment by chocoelho** [comment]
This is already solved by the migration to CircleCI 2

**Pull request closed without merging**
