### PR TITLE
Replace django-naomi with Mailhog

### LINKED ISSUE #450: Use Mailhog for SMTP testing
**Is your feature request related to a problem? Please describe.**
Using Mailhog is a better and cleaner way to test and debug email delivery while developing.
https://github.com/mailhog/MailHog

**Describe the solution you'd like**
Remove django-naomi and place mailhog instead for email testing.

### PR DESCRIPTION
**Pull request by jhgv**
Works only when developing using Docker
Closes #450 

## Steps to test
- [ ] Run the project
- [ ] Run the backend shell
- [ ] Run the following snippet
```python
from django.core.mail import send_mail
send_mail(
    'Test subject',
    'Here is the test message.',
    'from@example.com',
    ['to@example.com'],
    fail_silently=False,
)
```
- [ ] Go to 127.0.0:8025 and check if the email has been sent

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires documentation updates.
- [ ] I have updated the documentation accordingly.
- [ ] My change requires dependencies updates.
- [ ] I have updated the dependencies accordingly.

### CODE REVIEW

**Comment by vanessa** [comment]
What do you think about keeping django-naomi (or using another Django alternative like [file backend](https://docs.djangoproject.com/en/2.2/topics/email/#file-backend)) for those who don't want to use docker? We use it with docker but we'd force people who don't in case they want to just send some emails.

**Comment by jhgv** [comment]
@vanessa I think it is better to use another alternative because django-naomi is deprecated. This other alternative you mentioned might be better and there is no need to install another lib.

**Comment by vanessa** [comment]
@jhgv Ah, nice. Didn't know about django-naomi being deprecated. I'm just worried about having the user with no option other than use docker just to spin up this service. If we don't need to worry about that, then you can ignore this :sweat_smile:

**Comment by rvlb** [comment]
Installing Mailhog [locally](https://github.com/mailhog/MailHog#installation) seems to be pretty straightforward, maybe we could point to this in our readme. Happy to add it there if that's the case.

Non-docker users must also configure postgres, redis, etc, so I think this shouldn't be a big issue.

**Pull request merged**
