### PR TITLE
Add issue templates

### LINKED ISSUE #194: Make use of issue templates

### PR DESCRIPTION
**Pull request by chocoelho**
## Description

As of now, we're not making use of issue templates which can be really useful for users. These are the default ones that GitHub offers, we can change, remove and add others according to our needs. Right now, only `Bug report` and `Feature request` were added.

## Motivation and Context

It'll make it easier to file issues, since users will be lead to proper describe the type of issue opened and describe it properly. Resolves #194.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires documentation updates.
- [ ] I have updated the documentation accordingly.
- [ ] My change requires dependencies updates.
- [ ] I have updated the dependencies accordingly.

### CODE REVIEW

**Comment by fjsj** [comment]
Can you review this @laisvarejao ?

**Comment by laisvarejao** [comment]
@fjsj yes!

**Comment by laisvarejao** [comment]
@chocoelho what about features that aren't related to problems, but are just improvements instead?

**Comment by chocoelho** [comment]
@laisvarejao taking a look on other issue templates, they tend to add only questions or regressions (see https://github.com/facebook/jest/tree/master/.github/ISSUE_TEMPLATE). Any suggestion on how would we deal with improvements requests?

**Comment by chocoelho** [comment]
Also, the description of `Feature_request.md` may lead to the idea of improvements as well, don't you think?

`Suggest an idea for this project`

**Comment by laisvarejao** [comment]
@chocoelho makes sense! LGTM!

**Pull request merged**
