### PR TITLE
Remove Make bundle

### LINKED ISSUE #109: Document how make bundle works
Many people get confused because `make bundle` never finishes. The README running the project section should mention that this is the expected behavior.

### PR DESCRIPTION
**Pull request by aericson**
## Description
Closes #109

### CODE REVIEW

**Comment by toguko** [comment]
Is necessary change the README.md at **Running the project**, removing the highlighted line below?

### Running the project

- `pip install -r requirements.txt`
- `npm install`
- `make bundle`  _**Remove this line**_
- `python manage.py runserver`

**Comment by aericson** [comment]
@toguko yes, it's necessary because we use `npm run start` instead.
See: #109

**Comment by chocoelho** [comment]
Thanks for the contribution @aericson. Indeed, using `make bundle` can be confusing and we can start using `npm run ...` instead. I'm just thinking right now about it, isn't `npm run dev` better suited than `npm run start` in this case? What are your thoughts on that @hugobessa @filipeximenes ?

**Comment by aericson** [comment]
`npm run start` is the standard for this.

It's what [https://github.com/facebookincubator/create-react-app](create-react-app) and other projects uses and is even documented at https://docs.npmjs.com/cli/start. In more recent versions of node you can even use it just as `npm start` instead.

**Pull request merged**
