### PR TITLE
chore(package): update eslint-plugin-react-hooks to version 2.2.0

### PR DESCRIPTION
**Pull request by joaopslins**
Closes #375

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires documentation updates.
- [ ] I have updated the documentation accordingly.
- [ ] My change requires dependencies updates.
- [ ] I have updated the dependencies accordingly.

### CODE REVIEW

**Comment by lucabezerra** [comment]
@joaopslins Not sure if you've seen this, but your build is broken (:

**Comment by jhgv** [comment]
@joaopslins I think this plugin cannot be updated to version 2.2.0 because **eslint-config-vinta** has a peer dependency for ^1.6.1. We could either update **eslint-config-vinta** or abort this update

**Comment by joaopslins** [comment]
@victorfsf may chime in here

**Comment by victorfsf** [comment]
@joaopslins @jhgv will update there

**Pull request closed without merging**
