### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by chocoelho**
* Fixed boilerplate template url in README
* Updated NPM dependencies
* Migrated all webpack config files to v2
* Migrated bootstrap-loader config file to v2
* Provide plugins due to a change in how bootstrap-loader loads components
* Fixed Heroku opbeat plan
* Fixed webpack bundle path when in prod

### CODE REVIEW

**Comment by chocoelho** [comment]
@filipeximenes as we discussed via email, here are the updates I made to the boilerplate in order to deploy it to Heroku and the updates to both bootstrap-loader and webpack

**Comment by aericson** [comment]
Hey,

thanks for this.

The bootstrap version is locked to alpha 4 because it is (don't know if still is)[1](https://github.com/shakacode/bootstrap-loader/issues/235)[2](https://github.com/shakacode/bootstrap-loader/issues/236) the last working version of bootstrap that worked fine with bootstrap-loader. Also bootstrap is making breaking changes while it's in alpha, so projects can't rely on "^", but lock the version of it.

To upgrade the boiler plate to webpack and bootstrap-loader to v2 I had this couple of requirements:
- webpack v2 stable release (happened a few weeks ago, yay!).
- bootstrap 4 beta release (it's on the last alpha, next release will be beta).
- bootstrap-loader v2 stable release. (or at least a version known to support the beta).

I'd sugest we hold this PR until those requirements are met.
If you can, could you submit the other changes that doesn't involve this in a separate PR?

Thanks!

**Comment by chocoelho** [comment]
sure @aericson, will do :) I'll test them in another project to check for breaking changes. Just to make sure: webpack v2 update will be held along both bootstrap and bootstrap-loader?

**Comment by aericson** [comment]
Well, if it works I don't see a problem using it. But we are going to come back to it eventually and we could do it all at once. Unless it's not a lot of trouble to change only the webpack. Up to you.

**Comment by fjsj** [comment]
@rsarai can you evaluate this discussion please?

**Comment by chocoelho** [comment]
This merge is going to be solved by #101

**Pull request closed without merging**
