### PR TITLE
Javascript Absolute Imports

### PR DESCRIPTION
**Pull request by hugobessa**
Adds the possibility of using absolute imports referencing local files

## Description
I added `assets/js` folder as a global module in configuration so we can use absolute imports from this folder in our files, not requiring relative paths. I also updated the components in the project to use absolute imports.

## Motivation and Context
Relative imports are great when you have a flat architectures. You you nest a little bit, move files become a nightmare.

## Steps to reproduce (if appropriate):
- Create js files with absolute imports

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aericson** [comment]
Just a question. This does not break relative imports right?

There are some cases where I think relative imports are preferably.

For example for `index.js` files that exports code from it's location all it's imports should be relative ie: `export UserModal from ./components/UserModal.js;`. This makes it clear it's exporting code from this directory and avoid bugs related to wrong paths.

Maybe a good rule could be:
Use relative paths if you can write the import without using `..`.

If you agree with this, can you revert the change on `assets/js/index.js`?

@filipeximenes since you proposed this in #97 could you give your opnion too?

**Comment by filipeximenes** [comment]
@aericson yes, agreed. Specially because we are tending to use a 'app' based architecture, with a folder per component (we will schedule a pyzza to discuss this).

```
├── app
├── event-list
│   ├── components
│   │   ├── UserProfile
│   │   │   ├── UserProfile.js
│   │   │   ├── index.js
│   │   │   └── style.scss
```

**Comment by fjsj** [comment]
Can we merge this @filipeximenes @hugobessa ?

**Comment by filipeximenes** [comment]
Yes

**Pull request merged**
